const teksten = [
    "De Oorzaken van Klimaatverandering: Klimaatverandering is een van de grootste uitdagingen van deze tijd en wordt voornamelijk veroorzaakt door menselijke activiteiten. De belangrijkste oorzaak is de toename van broeikasgassen, zoals koolstofdioxide (CO₂) en methaan (CH₄), die warmte vasthouden in de atmosfeer. Dit versterkte broeikaseffect zorgt ervoor dat de aarde steeds warmer wordt. De grootste bron van CO₂-uitstoot is de verbranding van fossiele brandstoffen, zoals steenkool, olie en gas. Deze brandstoffen worden veel gebruikt voor het opwekken van elektriciteit, het aandrijven van voertuigen en in de industrie. Daarnaast speelt ontbossing een grote rol: bomen nemen CO₂ op uit de lucht, maar als ze worden gekapt of verbrand, komt deze CO₂ weer vrij, waardoor de concentratie in de atmosfeer stijgt. Ook de landbouw en veeteelt dragen bij aan klimaatverandering. Koeien en schapen stoten veel methaan uit door hun spijsvertering, en dit gas is zelfs krachtiger dan CO₂ in het vasthouden van warmte. Bovendien leidt de productie van veevoer tot ontbossing, waardoor de opname van CO₂ afneemt en er meer broeikasgassen in de lucht komen. Een gevaarlijk gevolg van de opwarming is het smelten van permafrost, een laag bevroren grond in onder andere Siberië en Canada. In deze grond zitten enorme hoeveelheden methaan en CO₂ opgeslagen. Wanneer de permafrost smelt, komen deze gassen vrij, wat de opwarming verder versnelt in een vicieuze cirkel. Sommige mensen denken dat de veranderingen in de zon de belangrijkste oorzaak zijn van de opwarming van de aarde, maar wetenschappelijk onderzoek heeft aangetoond dat dit niet zo is. Hoewel de zon natuurlijke variaties kent, is de huidige opwarming grotendeels het gevolg van menselijke uitstoot van broeikasgassen. Het is duidelijk dat menselijke activiteiten zoals het verbranden van fossiele brandstoffen, ontbossing en de veeteelt de belangrijkste oorzaken zijn van klimaatverandering. Als we de opwarming van de aarde willen beperken, moeten we overstappen op duurzame energiebronnen, bossen beschermen en duurzamer omgaan met voedselproductie.",
    "Gevolgen van klimaatverandering: Klimaatverandering is een van de grootste uitdagingen van deze tijd. Door de opwarming van de aarde ondervinden zowel de natuur als de mensheid ernstige gevolgen. Extreme weersomstandigheden, zoals hittegolven, orkanen en overstromingen, komen steeds vaker voor en worden heftiger. Dit leidt niet alleen tot schade aan infrastructuur, maar bedreigt ook mensenlevens. De stijging van de zeespiegel vormt daarnaast een groot gevaar voor laaggelegen gebieden en eilanden, die steeds meer risico lopen op overstromingen en landverlies. Een ander groot probleem is de toenemende droogte en watertekorten. Door langere en hevigere droogteperiodes dalen de landbouwopbrengsten en komt de beschikbaarheid van drinkwater onder druk te staan. Dit heeft niet alleen gevolgen voor de voedselzekerheid, maar draagt ook bij aan biodiversiteitsverlies. Veel dier- en plantensoorten kunnen zich niet snel genoeg aanpassen aan de veranderende temperaturen en leefomgevingen, wat leidt tot uitsterving of gedwongen migratie. De impact op de landbouw is aanzienlijk, aangezien mislukte oogsten steeds vaker voorkomen door extreme weersomstandigheden. Dit zorgt voor stijgende voedselprijzen en tekorten, wat de meest kwetsbare bevolkingsgroepen het hardst treft. Daarnaast brengt klimaatverandering ernstige gezondheidsrisico’s met zich mee. Warme temperaturen verergeren luchtvervuiling en verhogen het risico op hittegerelateerde ziektes, terwijl infectieziekten zich door veranderende klimaatomstandigheden gemakkelijker kunnen verspreiden. Ook ecosystemen worden ontwricht. Koraalriffen sterven af door oceaanverzuring en opwarming, terwijl bossen steeds vaker worden bedreigd door droogte en bosbranden. Deze veranderingen hebben niet alleen ecologische gevolgen, maar ook economische. De kosten voor herstel na natuurrampen blijven stijgen, en sectoren zoals landbouw en toerisme ondervinden grote schade door veranderende klimaatomstandigheden.",
    "Maatregelen tegen klimaatverandering: Klimaatverandering wordt grotendeels veroorzaakt door de uitstoot van broeikasgassen, zoals CO₂ en methaan. Er zijn verschillende maatregelen die zowel individuen als bedrijven kunnen nemen om deze uitstoot te verminderen. Fossiele brandstoffen zoals aardolie en steenkool veroorzaken veel CO₂-uitstoot. Door over te stappen op hernieuwbare energiebronnen, zoals zonne- en windenergie, kunnen we deze uitstoot aanzienlijk verminderen. Kernenergie wordt soms gezien als een alternatief, maar het nadeel is dat het radioactief afval produceert. Energie besparen is een effectieve manier om de impact op het klimaat te verkleinen. Dit kan door korter te douchen, apparaten uit te schakelen als ze niet worden gebruikt en gebouwen beter te isoleren. Bedrijven kunnen hun uitstoot verminderen door werknemers vaker thuis te laten werken en energiezuinige productiemethoden te gebruiken. Vervoer is een grote bron van broeikasgasuitstoot. Het verminderen van vliegreizen heeft een grote impact, net als het overstappen op elektrische auto's, fietsen of openbaar vervoer. De landbouwsector is wereldwijd een van de grootste veroorzakers van broeikasgassen. Vooral de veehouderij draagt bij aan klimaatverandering, omdat koeien en schapen veel methaan uitstoten. Minder vlees eten helpt om deze uitstoot te verminderen. Ook de bescherming van bossen is belangrijk, omdat bomen CO₂ opnemen en de lucht zuiveren. Een circulaire economie betekent dat materialen zoveel mogelijk hergebruikt worden in plaats van weggegooid. Dit helpt de industrie om minder nieuwe grondstoffen te gebruiken en de CO₂-uitstoot te verlagen. Ook consumenten kunnen bijdragen door minder afval te produceren en producten langer te gebruiken. Waterzuivering en -transport kosten veel energie. Door water te besparen, zoals door korter te douchen, helpt dit indirect om de uitstoot van broeikasgassen te verlagen. Door samen te werken en bewuste keuzes te maken, kunnen we de impact van klimaatverandering beperken en zorgen voor een duurzamere toekomst."
];

let huidigeIndex = 0;

function veranderTekst() {
    huidigeIndex = (huidigeIndex + 1) % teksten.length;
    document.getElementById('info-tekst').textContent = teksten[huidigeIndex];
}

document.querySelector('.pijl').addEventListener('click', veranderTekst);